name: OneInTheDodge
version: '1.0'
main: me.betun.oneinthedodge.OneInTheDodge
api-version: '1.20'
commands:
  reset:
    description: Reset al shrink-start
    usage: /reset
    permission: default
  recargar:
    description: Recarga la config
    usage: /recargar
    permission: default